export const loginConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  UPDATEUSERIMAGE_REQUEST: "UPDATEUSERIMAGE_REQUEST",
  UPDATEUSERIMAGE_SUCCESS: "UPDATEUSERIMAGE_SUCCESS",
  UPDATEUSERIMAGE_FAILURE: "UPDATEUSERIMAGE_FAILURE",
  UPDATENAME_REQUEST: "UPDATENAME_REQUEST",
  UPDATENAME_SUCCESS: "UPDATENAME_SUCCESS",
  UPDATENAME_FAILURE: "UPDATENAME_FAILURE",
  UPDATEPASSWORD_REQUEST: "UPDATEPASSWORD_REQUEST",
  UPDATEPASSWORD_SUCCESS: "UPDATEPASSWORD_SUCCESS",
  UPDATEPASSWORD_FAILURE: "UPDATEPASSWORD_FAILURE",
  UPDATEUMUR_REQUEST: "UPDATEUMUR_REQUEST",
  UPDATEUMUR_SUCCESS: "UPDATEUMUR_SUCCESS",
  UPDATEUMUR_FAILURE: "UPDATEUMUR_FAILURE",
  UPDATETELEPON_REQUEST: "UPDATETELEPON_REQUEST",
  UPDATETELEPON_SUCCESS: "UPDATETELEPON_SUCCESS",
  UPDATETELEPON_FAILURE: "UPDATETELEPON_FAILURE",
  UPDATETANGGALLAHIR_REQUEST: "UPDATETANGGALLAHIR_REQUEST",
  UPDATETANGGALLAHIR_SUCCESS: "UPDATETANGGALLAHIR_SUCCESS",
  UPDATETANGGALLAHIR_FAILURE: "UPDATETANGGALLAHIR_FAILURE",
  UPDATEALAMAT_REQUEST: "UPDATEALAMAT_REQUEST",
  UPDATEALAMAT_SUCCESS: "UPDATEALAMAT_SUCCESS",
  UPDATEALAMAT_FAILURE: "UPDATEALAMAT_FAILURE",
};

export const logoutConstant = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstant = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};

export const categoryConstant = {
  GETALLCATEGORY: "GETALLCATEGORY",
  GETALLCATEGORY_REQUEST: "GETALLCATEGORY_REQUEST",
  ADDCATEGORY_REQUEST: "ADDCATEGORY_REQUEST",
  ADDCATEGORY_SUCCESS: "ADDCATEGORY_SUCCESS",
  ADDCATEGORY_FAILURE: "ADDCATEGORY_FAILURE",
  DELETECATEGORY_REQUEST: "DELETECATEGORY_REQUEST",
  DELETECATEGORY_SUCCESS: "DELETECATEGORY_SUCCESS",
  DELETECATEGORY_FAILURE: "DELETECATEGORY_FAILURE",
  UPDATECATEGORY_REQUEST: "UPDATECATEGORY_REQUEST",
  UPDATECATEGORY_SUCCESS: "UPDATECATEGORY_SUCCESS",
  UPDATECATEGORY_FAILURE: "UPDATECATEGORY_FAILURE",
  DELETEALLCATEGORY_REQUEST: "DELETEALLCATEGORY_REQUEST",
  DELETEALLCATEGORY_SUCCESS: "DELETEALLCATEGORY_SUCCESS",
  DELETEALLCATEGORY_FAILURE: "DELETEALLCATEGORY_FAILURE",
};

export const chatConstant = {
  GETALLCHAT: "GETALLCHAT",
  OUTPUTCHAT: "OUTPUTCHAT",
};

export const productConstant = {
  GETALLPRODUCT_SUCCESS: "GETALLPRODUCT_SUCCESS",
  ADDPRODUCT_REQUEST: "ADDPRODUCT_REQUEST",
  ADDPRODUCT_SUCCESS: "ADDPRODUCT_SUCCESS",
  ADDPRODUCT_FAILURE: "ADDPRODUCT_FAILURE",
  DELETEPRODUCT_REQUEST: "DELETEPRODUCT_REQUEST",
  DELETEPRODUCT_SUCCESS: "DELETEPRODUCT_SUCCESS",
  DELETEPRODUCT_FAILURE: "DELETEPRODUCT_FAILURE",
  UPDATEPRODUCT_REQUEST: "UPDATEPRODUCT_REQUEST",
  UPDATEPRODUCT_SUCCESS: "UPDATEPRODUCT_SUCCESS",
  UPDATEPRODUCT_FAILURE: "UPDATEPRODUCT_FAILURE",
};
